#!/bin/sh
#
### BEGIN INIT INFO
# Provides: hyperic
# Required-Start:
# Required-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start the Jira Hook daemon
### END INIT INFO
HOOKS_USER=root
start() {
    echo 'starting....'
    su -l $HOOKS_USER -c '/usr/local/bin/python /home/CROSSVIEW/cfrasure/jira-hook/hooks.py start'
}
stop() {
    echo 'stopping...'
    su -l $HOOKS_USER -c '/usr/local/bin/python /home/CROSSVIEW/cfrasure/jira-hook/hooks.py stop' 
}
status() {
    su -l $HOOKS_USER -c '/usr/local/bin/python /home/CROSSVIEW/cfrasure/jira-hook/hooks.py status'
}
# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    condrestart)
        ;;
    reload)
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        ;;
esac
exit $RETVAL
